name: Drata IaC Scan

on:
  push:
    branches:
      - main  # Or your working branch

jobs:
  drata-iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Drata IaC Scan
        uses: drata/compliance-as-code-action@v1.0.0
        env:
          DRATA_API_TOKEN: ${{ secrets.DRATA_IAC_PIPELINE_KEY }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minimumSeverity: 'HIGH'
